[versions]
compileSdk = "35"
minSdk = "26"
targetSdk = "35"

#core
kotlin = "2.1.10"
coroutines = "1.10.1"
navigation = "2.9.0"

#libraries
coreKtx = "1.16.0"
activityKtx = "1.10.1"
appCompat = "1.7.0"
material = "1.12.0"
retrofit = "2.11.0"
retrofitGsonConverter = "2.11.0"
okHttp = "4.12.0"
timber = "5.0.1"
lottie = "6.6.7"
lifecycle = "2.9.0"
coil = "2.7.0"
room = "2.7.1"
activityCompose = "1.10.1"
compose = "1.8.1"
composeLifecycle = "2.9.0"
viewmodelCompose = "2.9.0"
navigationCompose = "2.9.0"
materialIconsExtended = "1.7.8"
hilt = "2.55"
hiltCompiler = "1.2.0"
hiltNavCompose = "1.2.0"
customChromeTab = "1.8.0"
firebase = "33.13.0"
datastore = "1.1.7"
gmsPlayServicesAds = "18.2.0"
playServicesBasement = "18.5.0"
accompanistWebview = "0.36.0"
accompanistPermissions = "0.37.0"
workManager = "2.10.1"
hiltWork = "1.2.0"
apacheCommonsText = "1.9"
adyenVersion = "4.13.3"
indicative = "1.1.0"
mintegral = "16.9.51"
zoomable = "2.0.0"
palette = "1.0.0"
credentials = "1.3.0"
googleId = "1.1.1"
playServicesAuth = "21.4.0"

#test libraries
junit = "4.13.2"
junit5 = "5.11.3"
turbine = "1.2.0"

#plugins
applicationGradlePlugin = "8.10.1"
kotlinAndroidGradlePlugin = "2.0.21"
androidGradlePlugin = "8.5.2"
hiltAndroidGradlePlugin = "2.52"
googleServicesPlugin = "4.4.2"
firebaseCrashlyticsGradle = "3.0.3"
androidJunit5Plugin = "1.9.3.0"
kspPlugin = "2.1.0-1.0.29"
lifecycleService = "2.9.3"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
app-compat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitGsonConverter" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
material-compose = { module = "androidx.compose.material:material", version.ref = "compose" }
animation-compose = { module = "androidx.compose.animation:animation", version.ref = "compose" }
ui-tooling-compose = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-compose = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycle" }
ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodelCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavCompose" }
hilt-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
custom-chrome-tab = { module = "androidx.browser:browser", version.ref = "customChromeTab" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-config = { module = "com.google.firebase:firebase-config" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
gms-play-services-ads = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "gmsPlayServicesAds" }
play-services-basement = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBasement" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
indicative-sdk = { module = "com.indicative.client.android:Indicative-Android", version.ref = "indicative" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
mintegral = { module = "com.mbridge.msdk.oversea:mbridge_android_sdk", version.ref = "mintegral" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-playServices = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleId = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }


#Test library dependencies
junit = { module = "junit:junit", version.ref = "junit" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-jupiter-vantage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

#root / build-logic
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
android-junit5-plugin = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "androidJunit5Plugin" }
google-services-plugin = { module = "com.google.gms:google-services", version.ref = "googleServicesPlugin" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
ksp-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "kspPlugin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }

[plugins]
android-application = { id = "com.android.application", version.ref = "applicationGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "applicationGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5Plugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidGradlePlugin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidGradlePlugin" }

android-module = { id = "android-module" }
composable = { id = "composable" }
hilt = { id = "hilt" }
tests = { id = "tests" }

[bundles]
firebase = ["firebase-analytics", "firebase-crashlytics", "firebase-messaging", "firebase-config"]
